# Generated by Django 5.0.6 on 2024-05-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_venues',
            field=models.ManyToManyField(related_name='favorited_by', to='core.venue'),
        ),
    ]
