# Generated by Django 5.0.6 on 2024-05-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_favorite_venues'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='iframe_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='localization',
            field=models.CharField(default='Unknown Location', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='open_hours',
            field=models.CharField(default='xd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='visit_code',
            field=models.CharField(default=4321, max_length=4),
            preserve_default=False,
        ),
    ]
