# Generated by Django 5.0.6 on 2024-05-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_venue_iframe_link_venue_localization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='localization',
            field=models.CharField(max_length=300),
        ),
    ]
