# Generated by Django 5.0.6 on 2024-05-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_venue_localization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='localization',
            field=models.CharField(max_length=400),
        ),
    ]
